version: "3"

services:
  database:
    image: mariadb:10
    ports:
      - "10306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=blog1234
      - MARIADB_ROOT_HOST=%
      - MARIADB_DATABASE=blog_schema
  flask_server:
    build: docker_flask_server
    depends_on:
      - database
    ports:
      - "7001:7000"

